ooo_standart_project/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('requisites', views.RequisiteViewSet)
router.register('invoices', views.PaymentRequestViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

ooo_standart_project/ooo_standart_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('request.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

ooo_standart_project/request/urls.py
from django.urls import path

from . import views

app_name = 'request'

urlpatterns = [
    path(
        '',
        views.PaymentPage.as_view(),
        name='payment'
    ),
    path(
        'requisite/',
        views.RequsitePage.as_view(),
        name='requisite'
    ),
    path(
        'search/',
        views.RequsitePage.as_view(),
        name='search'
    ),
    path(
        'profile/<str:username>/',
        views.UserProfileView.as_view(),
        name='profile'
    ),
    path(
        'profile/<str:username>/edit/',
        views.EditProfileView.as_view(),
        name='edit_profile'
    ),

]

ooo_standart_project/request/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

from api.constants import (STATUS_CHOICES, PAYMENT_CHOICES,
                           ACCOUNT_TYPE, REQUISITE_MAX_LENGTH)


class Requisite(models.Model):
    """ Модель реквизитов. """

    payment_type = models.CharField(
        'Тип платежа', choices=PAYMENT_CHOICES,
        max_length=REQUISITE_MAX_LENGTH)

    account_type = models.CharField(
        'Тип карты/счёта', choices=ACCOUNT_TYPE,
        max_length=REQUISITE_MAX_LENGTH)

    first_name = models.CharField('Имя', max_length=REQUISITE_MAX_LENGTH)
    last_name = models.CharField('Фамилия', max_length=REQUISITE_MAX_LENGTH)
    middle_name = models.CharField(
        'Отчество', max_length=REQUISITE_MAX_LENGTH, blank=True)
    phone_number = PhoneNumberField()
    card_limit = models.DecimalField(
        'Лимит доступных средств', max_digits=10, decimal_places=2)
    created = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'Реквизиты'
        verbose_name_plural = 'Реквизиты'
        ordering = ('-created',)

    def __str__(self) -> str:
        return f'{self.last_name} {self.first_name}, тел.: {self.phone_number}'


class PaymentRequest(models.Model):
    """ Модель заявки на оплату. """

    amount = models.DecimalField(
        'Сумма оплаты', max_digits=10, decimal_places=2)
    requisites = models.ForeignKey(
        Requisite,
        on_delete=models.PROTECT,
        verbose_name='Реквизиты заявки')

    status = models.CharField(
        'Статус заявки', choices=STATUS_CHOICES,
        max_length=REQUISITE_MAX_LENGTH, default=STATUS_CHOICES[0])

    created = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        ordering = ('-created',)

    def __str__(self) -> str:
        return f'{self.requisites} {self.status}'

ooo_standart_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator

from api.constants import (
    REQUIRED_FIELDS, MAX_USER_MODEL_FIELD_LENGTH, USER, USER_ROLES)


class CustomUser(AbstractUser):
    """ Кастомная модель пользователя. """

    REQUIRED_FIELDS = REQUIRED_FIELDS

    username = models.CharField(
        'Логин',
        max_length=MAX_USER_MODEL_FIELD_LENGTH,
        unique=True,
        validators=[UnicodeUsernameValidator()]
    )

    password = models.CharField(
        'Пароль', max_length=MAX_USER_MODEL_FIELD_LENGTH)

    first_name = models.CharField(
        'Имя', max_length=MAX_USER_MODEL_FIELD_LENGTH)
    last_name = models.CharField(
        'Фамилия', max_length=MAX_USER_MODEL_FIELD_LENGTH)

    role = models.CharField('Роль', max_length=50,
                            choices=USER_ROLES, default=USER)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return self.username

ooo_standart_project/request/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
        )

ooo_standart_project/request/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from .models import Requisite, PaymentRequest
from .forms import UserForm

User = get_user_model()


class PaymentPage(LoginRequiredMixin, ListView):
    template_name = 'request/payment.html'
    model = PaymentRequest
    paginate_by = 10

    def get_queryset(self):
        return PaymentRequest.objects.select_related(
            'requisites'
        )


class RequsitePage(ListView):
    template_name = 'request/requsite.html'
    model = Requisite
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        order_by = self.request.GET.get('order_by')
        if q:
            q_lst = q.split(",")
            return queryset.filter(Q(payment_type__in=q_lst) |
                                   Q(account_type__in=q_lst) |
                                   Q(first_name__in=q_lst) |
                                   Q(last_name__in=q_lst) |
                                   Q(phone_number__in=q_lst)
                                   )
        if order_by:
            return queryset.order_by(order_by)
        return queryset


class UserProfileView(LoginRequiredMixin, ListView):
    template_name = 'request/profile.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_object_or_404(
            User, username=self.kwargs['username'])
        return context


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'request/user.html'

    def get_object(self, queryset=None):
        return get_object_or_404(User)

    def get_success_url(self) -> str:
        return reverse_lazy('request:profile')

ooo_standart_project/users/views.py
from django.shortcuts import render

# Create your views here.

ooo_standart_project/templates/request/index.html
{% extends "base.html" %}
{% block title %}
  Лента заявок
{% endblock %}
{% block content %}
  {% for payment in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

ooo_standart_project/templates/request/payment.html
{% extends "base.html" %}
{% block title %}
  Лента заявок
{% endblock %}
{% block content %}
  {% for payment in page_obj %}
    <article class="mb-5">
      {% include "includes/payment_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

ooo_standart_project/templates/request/profile.html
{% extends "base.html" %}
{% block title %}Страница пользователя {{ profile }}{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">
        Имя пользователя:
        {% if profile.get_full_name %}
          {{ profile.get_full_name }}
        {% else %}
          не указано
        {% endif %}
      </li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">
        Роль:
        {% if profile.is_staff %}
          Админ
        {% else %}
          Пользователь
        {% endif %}
      </li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
        <a class="btn btn-sm text-muted" href="{% url 'request:edit_profile' profile %}">Редактировать профиль</a>
        <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="btn btn-sm text-muted" href="{% url 'logout' %}">Выйти из учетной записи</a>
      {% endif %}
    </ul>
  </small>
  <br> 
  
{% endblock %}

ooo_standart_project/templates/request/requsite.html
{% extends "base.html" %}
{% block title %}
  Лента заявок
{% endblock %}
{% block content %}
  {% for requsite in page_obj %}
    <article class="mb-5">
      {% include "includes/requsite_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

ooo_standart_project/templates/request/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}